version: "3"

services:
  challenge-frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend/src:/app/src:delegated
      - ./frontend/public:/app/public:delegated
    ports:
      - 3000:3000
    container_name: challenge-frontend
    networks:
      - fullstack-challenge
  challenge-api:
    container_name: challenge-api
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    command:
      [
        "uvicorn",
        "fullstack_challenge_api.main:app",
        "--port=20002",
        "--host=0.0.0.0",
        "--reload"
      ]
    environment:
      COLUMNS: 164
    tty: true
    ports:
      - "20002:20002"
    volumes:
      - ./api/fullstack_challenge_api:/fullstack_challenge_api
      - ./api/config/config.toml:/config/config.toml
    networks:
      - fullstack-challenge

networks:
  fullstack-challenge:
